-
  name: Service Playbook
  hosts: all
  gather_facts: yes
  any_errors_fatal: true
  tasks:
    - name: ensure WORKING_DIR exists
      file:
        path: "{{ WORKING_DIR }}"
        state: directory

    - name: "Save generated inventory"
      copy:
        content: "{{ solace_broker_service_result.broker_service.inventory | to_nice_yaml(indent=2) }}"
        dest: "{{ WORKING_DIR }}/broker.inventory.yml"
